# Generated by Django 5.2.3 on 2025-11-16 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Varity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='imgs/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('KB', 'Kuroku Basketball'), ('ON', 'One Piece'), ('DR', 'Dragon Ball Z'), ('NT', 'Naruto'), ('AT', 'Attack on Titan'), ('DS', 'Demon Slayer')], max_length=2)),
            ],
        ),
    ]
