# Generated by Django 5.2.3 on 2025-11-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='varity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
